"""add inventory tables

Revision ID: 001d791c8c31
Revises: 19044f3eddf4
Create Date: 2026-06-18 21:03:39.190498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001d791c8c31'
down_revision = '19044f3eddf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('kubernetes_version', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cluster_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cluster_inventory_cluster_id'), ['cluster_id'], unique=False)

    op.create_table('namespace_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'namespace', name='uq_namespace_inventory_cluster_namespace')
    )
    with op.batch_alter_table('namespace_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_namespace_inventory_cluster_id'), ['cluster_id'], unique=False)

    op.create_table('node_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('os_image', sa.String(length=255), nullable=True),
    sa.Column('kernel_version', sa.String(length=255), nullable=True),
    sa.Column('container_runtime', sa.String(length=255), nullable=True),
    sa.Column('cpu', sa.Integer(), nullable=True),
    sa.Column('memory', sa.String(length=50), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'node_name', name='uq_node_inventory_cluster_node')
    )
    with op.batch_alter_table('node_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_node_inventory_cluster_id'), ['cluster_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('node_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_node_inventory_cluster_id'))

    op.drop_table('node_inventory')
    with op.batch_alter_table('namespace_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_namespace_inventory_cluster_id'))

    op.drop_table('namespace_inventory')
    with op.batch_alter_table('cluster_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cluster_inventory_cluster_id'))

    op.drop_table('cluster_inventory')
    # ### end Alembic commands ###
