"""add cluster metadata

Revision ID: 19044f3eddf4
Revises: bc632b10057c
Create Date: 2026-06-18 17:30:19.228088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19044f3eddf4'
down_revision = 'bc632b10057c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('server', sa.String(length=255), nullable=True))
        batch_op.add_column(
    sa.Column(
        "node_count",
        sa.Integer(),
        nullable=False,
        server_default="0"
    )
)
        batch_op.add_column(sa.Column('last_check', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_column('last_check')
        batch_op.drop_column('node_count')
        batch_op.drop_column('server')

    # ### end Alembic commands ###
