"""add storage inventory

Revision ID: 23aca2bdbaca
Revises: f4c24a412570
Create Date: 2026-06-21 10:45:44.288799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23aca2bdbaca'
down_revision = 'f4c24a412570'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('storage_type', sa.String(length=50), nullable=False),
    sa.Column('storage_class', sa.String(length=255), nullable=True),
    sa.Column('capacity', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'namespace', 'name', 'storage_type', name='uq_storage_inventory')
    )
    with op.batch_alter_table('storage_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_storage_inventory_cluster_id'), ['cluster_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_storage_inventory_cluster_id'))

    op.drop_table('storage_inventory')
    # ### end Alembic commands ###
