"""add node status and ephemeral storage inventory

Revision ID: 631b8ec6d909
Revises: ee130522a645
Create Date: 2026-06-26 20:38:17.240747

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '631b8ec6d909'
down_revision = 'ee130522a645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pods_cluster_id'))
        batch_op.drop_index(batch_op.f('ix_pods_namespace'))

    op.drop_table('pods')
    with op.batch_alter_table('node_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ephemeral_storage', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ephemeral_storage_allocatable', sa.String(length=50), nullable=True))

    with op.batch_alter_table('prometheus_configs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('prometheus_configs_cluster_id_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('prometheus_configs_cluster_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clusters', ['cluster_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prometheus_configs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('prometheus_configs_cluster_id_fkey'), 'clusters', ['cluster_id'], ['id'])
        batch_op.create_unique_constraint(batch_op.f('prometheus_configs_cluster_id_key'), ['cluster_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('node_inventory', schema=None) as batch_op:
        batch_op.drop_column('ephemeral_storage_allocatable')
        batch_op.drop_column('ephemeral_storage')
        batch_op.drop_column('status')

    op.create_table('pods',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cluster_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('namespace', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('node_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('pod_ip', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('restart_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('owner_kind', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('owner_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('pods_cluster_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pods_pkey')),
    sa.UniqueConstraint('cluster_id', 'namespace', 'name', name=op.f('uq_pod_cluster_namespace_name'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('pods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pods_namespace'), ['namespace'], unique=False)
        batch_op.create_index(batch_op.f('ix_pods_cluster_id'), ['cluster_id'], unique=False)

    # ### end Alembic commands ###
