"""add pod inventory

Revision ID: a35950f28399
Revises: 4e31f6b9901f
Create Date: 2026-06-21 08:44:35.520801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a35950f28399'
down_revision = '4e31f6b9901f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pod_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('pod_name', sa.String(length=255), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=True),
    sa.Column('phase', sa.String(length=50), nullable=True),
    sa.Column('pod_ip', sa.String(length=50), nullable=True),
    sa.Column('ready', sa.String(length=50), nullable=True),
    sa.Column('restart_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'namespace', 'pod_name', name='uq_pod_inventory')
    )
    with op.batch_alter_table('pod_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pod_inventory_cluster_id'), ['cluster_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pod_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pod_inventory_cluster_id'))

    op.drop_table('pod_inventory')
    # ### end Alembic commands ###
