"""add pod table

Revision ID: b76e51fbbcde
Revises: cfe39410fef2
Create Date: 2026-06-20 07:46:19.889092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76e51fbbcde'
down_revision = 'cfe39410fef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('node_name', sa.String(length=255), nullable=True),
    sa.Column('pod_ip', sa.String(length=50), nullable=True),
    sa.Column('restart_count', sa.Integer(), nullable=False),
    sa.Column('owner_kind', sa.String(length=50), nullable=True),
    sa.Column('owner_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'namespace', 'name', name='uq_pod_cluster_namespace_name')
    )
    with op.batch_alter_table('pods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pods_cluster_id'), ['cluster_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pods_namespace'), ['namespace'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('pods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pods_namespace'))
        batch_op.drop_index(batch_op.f('ix_pods_cluster_id'))

    op.drop_table('pods')
    # ### end Alembic commands ###
