"""add prometheus configuration

Revision ID: ba9442ef5585
Revises: 23aca2bdbaca
Create Date: 2026-06-22 17:53:54.436259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9442ef5585'
down_revision = '23aca2bdbaca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prometheus_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('bearer_token', sa.String(length=4096), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prometheus_configs')
    # ### end Alembic commands ###
