"""add service inventory

Revision ID: ba97163704e9
Revises: a35950f28399
Create Date: 2026-06-21 09:00:54.207692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba97163704e9'
down_revision = 'a35950f28399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=True),
    sa.Column('cluster_ip', sa.String(length=100), nullable=True),
    sa.Column('external_ip', sa.String(length=255), nullable=True),
    sa.Column('ports', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'namespace', 'service_name', name='uq_service_inventory')
    )
    with op.batch_alter_table('service_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_inventory_cluster_id'), ['cluster_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_inventory_cluster_id'))

    op.drop_table('service_inventory')
    # ### end Alembic commands ###
