"""add workload inventory

Revision ID: cfe39410fef2
Revises: 001d791c8c31
Create Date: 2026-06-18 22:27:33.271284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe39410fef2'
down_revision = '001d791c8c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workload_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=255), nullable=False),
    sa.Column('cluster_name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('workload_name', sa.String(length=255), nullable=False),
    sa.Column('workload_type', sa.String(length=50), nullable=False),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('ready_replicas', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workload_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workload_inventory_cluster_id'), ['cluster_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workload_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workload_inventory_cluster_id'))

    op.drop_table('workload_inventory')
    # ### end Alembic commands ###
