"""add ingress inventory

Revision ID: f4c24a412570
Revises: ba97163704e9
Create Date: 2026-06-21 10:35:28.859143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c24a412570'
down_revision = 'ba97163704e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingress_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('ingress_name', sa.String(length=255), nullable=False),
    sa.Column('ingress_class', sa.String(length=100), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('tls_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cluster_id', 'namespace', 'ingress_name', name='uq_ingress_inventory')
    )
    with op.batch_alter_table('ingress_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingress_inventory_cluster_id'), ['cluster_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingress_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingress_inventory_cluster_id'))

    op.drop_table('ingress_inventory')
    # ### end Alembic commands ###
