"""add alertmanager configuration

Revision ID: f56c0cf05b8b
Revises: 631b8ec6d909
Create Date: 2026-06-28 15:21:16.900678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f56c0cf05b8b'
down_revision = '631b8ec6d909'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alertmanager_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('auth_type', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('bearer_token', sa.Text(), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('verify_ssl', sa.Boolean(), nullable=False),
    sa.Column('last_status', sa.String(length=50), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alertmanager_configs', schema=None) as batch_op:
        batch_op.create_index('ix_alertmanager_configs_cluster_status', ['cluster_id', 'last_status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alertmanager_configs', schema=None) as batch_op:
        batch_op.drop_index('ix_alertmanager_configs_cluster_status')

    op.drop_table('alertmanager_configs')
    # ### end Alembic commands ###
